CREATE EVENT IF NOT EXISTS DakikalikGenelKontrol ON SCHEDULE EVERY 1 MINUTE STARTS CURRENT_TIMESTAMP ON COMPLETION PRESERVE ENABLE DO CALL AnaKontrol();
CREATE EVENT IF NOT EXISTS DakikalikRaporlama ON SCHEDULE EVERY 5 MINUTE STARTS CURRENT_TIMESTAMP ON COMPLETION PRESERVE ENABLE DO CALL AdminRaporMailiOlustur();
CREATE EVENT IF NOT EXISTS Test_Ceza_Kontrolu ON SCHEDULE EVERY 1 MINUTE STARTS CURRENT_TIMESTAMP ON COMPLETION NOT PRESERVE ENABLE DO BEGIN CALL ceza();
END;